### ISSUE TITLE
The employee Google Apps Script is missing six employees

### ISSUE THREAD

**Issue by GaurangTandon** [normalhuman/normalhuman.github.io#1]
I wrote a script - [as you had indicated to me today](https://stackapps.com/questions/7953/how-to-get-a-list-of-all-stackexchange-employees/7954?noredirect=1#comment16622_7954) - to fetch all employees. However, unexpectedly, I managed to scrape six more employees from the SE API than [your current Google Apps Script](https://script.google.com/macros/s/AKfycbxOAwY1_-cby5xiYDH1e452_NvypIq4n_uVn7RYg0M-ok_ajA/exec) does. Here's an [onlinediff](https://www.diffchecker.com/3n4aAYEJ) of Meta.SE employee user IDs. The user IDs on the right are from my new script, while those on the left were scraped from your GA Script.

The concerned (new) employees are:

- [173432 - Eliza](https://meta.stackexchange.com/users/173432/eliza)
- [208517 - Micah Siegel](https://meta.stackexchange.com/users/208517/micah-siegel)
- [286257 - Unibot](https://meta.stackexchange.com/users/286257/unibot)
- [292464 - Valerie](https://meta.stackexchange.com/users/292464/valerie)
- [294852 - George Carter](https://meta.stackexchange.com/users/294852/george-carter)
- [309381 - Annkatrin Stanner](https://meta.stackexchange.com/users/309381/annkatrin-stanner) 

This is a [link to my code](https://repl.it/@SigmaG/GetListOfAllEmployeesThroughAPI). (needs an access token and an api key)

I'm not sure what's causing the issue, because I don't know how exactly your GA Script functions. I really wished to blame caching, but then, employees like Valerie [have been at SO](https://www.linkedin.com/in/thevaleriethomas/) for more than an year now :/

**Comment by normalhuman** [comment]
173432 and 286257 are bots.
208517 is not an employee; he is an investor (one of early investors in SO), and advised the company regarding the Patents site, where he was given an employee-grade diamond.

My code suppresses the [173432, 208517, 286257]. 

I don't know how I missed the other three, but I just now noticed the weekly total scans that I expected to run did not actually run, so it's probably that. I'm not releasing code because Google Apps Script is quirky in general, my code is a mess on top of that, and its structure is tied to the structure of my private spreadsheet,

**Comment by GaurangTandon** [comment]
Alright, not a problem. And thanks for the quick resolution.
